// leave off @2x/@3x
const images = {
    userDefault: require('../Images/userDefault.png'),
    location: require('../Images/location.png'),
    car: require('../Images/car.jpg'),
    car1: require('../Images/car1.png'),
    car2: require('../Images/car2.png'),
    car3: require('../Images/car3.png'),
    car4: require('../Images/car4.png'),
    car5: require('../Images/car5.png'),
    profile : require('../Images/profile.jpg'),
    placeholder : require('../Images/placeholder.png'),
    route : require('../Images/route.png'),
    clock : require('../Images/clock.png'),
    calendar : require('../Images/calendar.png'),
    icon1 : require('../Images/icon1.png'),
    icon2 : require('../Images/icon2.png'),
    icon3 : require('../Images/icon3.png'),
    icon4 : require('../Images/icon4.png'),
    icon : require('../Images/icon.png'),
    mapmark : require('../Images/mapmark.png'),
    threeman : require('../Images/threeman.png'),
    payment : require('../Images/payment.png'),
    carcheck : require('../Images/carcheck.png'),
    minute : require('../Images/minute.png'),
    road : require('../Images/road.png'),
    jan : require('../Images/jan.png'),
    pin : require('../Images/pin.png'),
    carIcon : require('../Images/carIcon.png'),
    carIcon2 : require('../Images/carIcon2.png'),
    carIcon3 : require('../Images/carIcon3.png'),
    default : require('../Images/default.png'),
    currentLocation : require('../Images/currentLocation.png'),
    slocation : require('../Images/slocation.png'),
    selectStar : require('../Images/selectStar.png'),
    grayStar : require('../Images/grayStar.png'),
    edit : require('../Images/edit.png'),
    back : require('../Images/back.png'),
    fromto: require('../Images/fromto.png'),
    marker: require('../Images/marker.png')
}

export default images
